config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  root 'offers#index'

  get 'contact' => 'pages#contact'

  resources :offers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  has_one_attached :image, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :country, presence: true
  validates :location, presence: true
  validates :meals, presence: true
  validates :host_name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :stars, presence: true, inclusion: 1..5
  validates :cleaning, presence: true, inclusion: 0..100
  validates :food, presence: true, inclusion: 0..100
  validates :staff, presence: true, inclusion: 0..100
  validates :confort, presence: true, inclusion: 0..100
  validates :minimum_stay, presence: true, numericality: { greater_than_or_equal_to: 1 }

  def get_rating(offer)
    (offer.cleaning + offer.food + offer.staff + offer.confort) / 4
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/offers_controller.rb
# frozen_string_literal: true

class OffersController < ApplicationController
  # before_action :authenticate_user!, only: %i[ new edit update destroy ]
  before_action :set_offer, only: %i[show edit update destroy]

  # GET /offers or /offers.json
  def index
    @offers = Offer.all.with_attached_image
  end

  # GET /offers/1 or /offers/1.json
  def show; end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit; end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def offer_params
    params.require(:offer).permit(:name, :description, :phone, :email, :country, :location, :meals, :price, :stars,
                                  :rating, :cleaning, :food, :staff, :confort, :host_name, :minimum_stay, :image)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def contact; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/offers_helper.rb
# frozen_string_literal: true

module OffersHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transylvanian Resorts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :meals %>
    <%= form.text_field :meals %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :stars %>
    <%= form.text_field :stars %>
  </div>

  <div class="field">
    <%= form.label :cleaning %>
    <%= form.text_field :cleaning %>
  </div>

  <div class="field">
    <%= form.label :food %>
    <%= form.text_field :food %>
  </div>

  <div class="field">
    <%= form.label :staff %>
    <%= form.text_field :staff %>
  </div>

  <div class="field">
    <%= form.label :confort %>
    <%= form.text_field :confort %>
  </div>

  <div class="field">
    <%= form.label :host_name %>
    <%= form.text_field :host_name %>
  </div>

  <div class="field">
    <%= form.label :minimum_stay %>
    <%= form.text_field :minimum_stay %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<section class="form-style">
  <h1>Editing Offer</h1>

  <%= render 'form', offer: @offer %>

  <%= link_to 'Show', @offer %> |
  <%= link_to 'Back', offers_path %>
</section>

app/views/offers/index.html.erb
<header class="main-header">
    <nav class="main-nav">
        <figure class="nav-logo">
            <a href="#"><%= image_tag("logo.png", class: "logo invert-color", alt: "logo-image-small") %></a>
        </figure>
        <ul>
            <li><%= link_to offers_path do %>Home<% end %></li>
            <li><a>|</a></li>
            <li><%= link_to contact_path do %>Contact<% end %></li>
            <% if current_user %>
                <li><a>|</a></li>
                <li><%= link_to destroy_user_session_path, method: :delete do %>Logout<% end %></li>
                <li><a>|</a></li>
                <li><%= link_to edit_user_registration_path do %>Edit User<% end %></li>
                <li><a>|</a></li>
                <li><a>Welcome <%= current_user.email %></a></li>
            <% else %>
                <li><a>|</a></li>
                <li><%= link_to new_user_session_path do %>Login<% end %></li>
            <% end %>
        </ul>
    </nav>
    <figure class="cover">
        <h1 class="motto">Your Journey Beginns with Us</h1>
    </figure>
</header>

<main class="main-content">
    <h2>Check our Offers</h2>
    <section class="main-offers">
        <% @offers.each do |offer| %>
          <figure class="offer-container">
              <%= link_to offer do %>
                  <% if offer.image.attached? %>
                    <td><%= image_tag offer.image, class: "main-offers-img" %></td>
                  <% end %>
                  <div class="offer-container-box">
                      <div class="offer-box-column">
                          <strong><%= offer.location%> / <%= offer.country%></strong>
                          <strong><%= offer.name%></strong>
                      </div>
                      <div class="offer-box-column">
                          <strong><%= offer.meals%></strong>
                          <strong>$ <%= offer.price%> / night</strong>
                      </div>
                  </div>
              <% end %>
          </figure>
        <% end %>
    </section>
</main>

<footer class="main-footer">
    <section class="footer-upper-part">
        <section class="main-logo-motto">
            <%= image_tag("logo.png", alt: "logo-image-big")%>
            <%= image_tag("motto.png", alt: "motto")%>
        </section>

        <section class="contact-us">
            <h2>Contact Us</h2>
            <section class="contact-item">
                <%= image_tag("icon-phone.png", alt: "phone-logo")%>
                <a href="tel:+123456789012">+ 1234 5678 9012</a>
            </section>
            <section class="contact-item">
                <%= image_tag("icon-email.png", alt: "email-logo", width: "50", height: "50")%>
                <a href="mailto:contact@travel.com">contact@travel.com</a>
            </section>
        </section>
    </section>
    <nav class="footer-nav">
        <ul>
            <li><a href="#"><%= image_tag("icon-facebook.png", alt: "facebook-logo", width: "70", height: "70")%></a></li>
            <li><a href="#"><%= image_tag("icon-instagram.png", alt: "instagram-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("icon-twitter.png", alt: "twitter-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("icon-youtube.png", alt: "youtube-logo", width: "60", height: "60")%></a></li>
            <li id="copyright">Copyright @2021</li>
        </ul>
    </nav>
</footer>
<% if current_user %>
    <br><br><br>

    <section class="form-style">

        <p id="notice"><%= notice %></p>

        <h1>Offers</h1>

        <table>
        <thead>
            <tr>
            <th>Name</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Country</th>
            <th>Location</th>
            <th>Host name</th>
            <th>Image</th>
            <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% @offers.order(:id).each do |offer| %>
            <tr>
                <td><%= offer.name %></td>
                <td><%= offer.phone %></td>
                <td><%= offer.email %></td>
                <td><%= offer.country %></td>
                <td><%= offer.location %></td>
                <td><%= offer.host_name %></td>
                <% if offer.image.attached? %>
                <td><%= image_tag offer.image.variant(resize: "500x500") %></td>
                <% end %>
                <td><%= link_to 'Show', offer %></td>
                <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
                <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
        </tbody>
        </table>

        <br>

        <%= link_to 'New Offer', new_offer_path %>
    </section>
<% end %>

app/views/offers/new.html.erb
<section class="form-style">
  <h1>New Offer</h1>

  <%= render 'form', offer: @offer %>

  <%= link_to 'Back', offers_path %>
</section>

app/views/offers/show.html.erb
<header class="main-header" id="anchorUp">
    <nav class="main-nav">
        <figure class="nav-logo">
            <a href="#"><%= image_tag("logo.png", alt: "logo-image-small", class: "logo invert-color")%></a>
        </figure>
        <ul>
            <li><%= link_to offers_path do %>Home<% end %></li>
            <li><a>|</a></li>
            <li><%= link_to contact_path do %>Contact<% end %></li>
        </ul>
    </nav>
</header>

<main class="main-content-page">
  <section class="up">
  <section class="page">
    <section class="line">
      <strong>
        <%= @offer.location %>, <%= @offer.country %>
      </strong>
    </section>
    <section class="resort">
      <h2>
        <%= @offer.name %>
      </h2>
      <section class="stars">
        <% for i in 1..5 do %>
          <% if i <= @offer.stars %>
            &#9733;
          <% else %>
            &#9734;
          <% end%>
        <% end %>
      </section>
      <section class="amenities">
        <div class="progress" data-label="Overall Rating">
          <span class="value" style="width:<%= @offer.get_rating(@offer) %>%;"></span>
        </div>
        <div class="progress" data-label="Cleaning">
          <span class="value" style="width:<%= @offer.cleaning %>%;"></span>
        </div>
        <div class="progress" data-label="Food">
          <span class="value" style="width:<%= @offer.food %>%;"></span>
        </div>
        <div class="progress" data-label="Staff">
          <span class="value" style="width:<%= @offer.staff %>%;"></span>
        </div>
        <div class="progress" data-label="Confort">
          <span class="value" style="width:<%= @offer.confort %>%;"></span>
        </div>
      </section>
      <section class="description">
        <p>
          <%= @offer.description%>
        </p>
        <p class="tags">
          #mountain #PiatraCraiului #quiet #guidedTours
        </p>
      </section>
    </section>
    <section class="details">
      <section class="price">
        <h2>$ <p id="offer-price"><%= @offer.price %><p> / night</h2>
      </section>
      <section class="host-details">
        <section class="details-item">
          <%= image_tag("icon-user.png", alt: "user-logo", width: 50, height: 50, class: "invert-color")%>
          <div class="details-item-text">
            <h3>Your host</h3>
            <h3><%= @offer.host_name %></h3>
          </div>
        </section>
        <section class="details-item">
          <%= image_tag("icon-clock.png", alt: "clock-logo", width: 50, height: 50, class: "invert-color")%>
          <div class="details-item-text">
            <h3>Minimum stay</h3>
            <h3><%= @offer.minimum_stay %> nights</h3>
          </div>
        </section>
        <section class="details-item">
          <%= image_tag("icon-placeholder.png", alt: "placeholder-logo", width: 50, height: 50, class: "invert-color")%>
          <div class="details-item-text">
            <h3>Location</h3>
            <h3><%= @offer.country %></h3>
          </div>
        </section>
      </section>
    </section>
  </section>

  <section class="buttons">
    <section class="button-back">
      <%= link_to offers_path do %>
          <%= image_tag("icon-arrow.png", alt: "arrow-logo", width: 40, height: 40, class: "rotate90")%>
          <h3>Back to Resort Listing</h3>
      <% end %>
    </section>
    <section class="button-book">
      <a href="#anchor">
        <h3>Book a Room</h3>
        <%= image_tag("icon-arrow.png", alt: "arrow-logo", width: 40, height: 40)%>
      </a>
    </section>
  </section>
  </section>
  <section class="buttons" id="anchor">
    <section class="button-back-resort displaynone">
      <a href="#anchorUp">
        <%= image_tag("icon-arrow.png", alt: "arrow-logo", width: 40, height: 40, class: "rotate180")%>
        <h3>Back to Resort</h3>
      </a>
    </section>
  </section>

  <section class="page-down">
    <section class="line">
      <strong>
        Booking
      </strong>
    </section>
    <section class="resort">
      <h3>Book your room at</h3>
      <h2><%= @offer.name %></h2>
      <section class="stars">
        <% for i in 1..5 do %>
          <% if i <= @offer.stars %>
            &#9733;
          <% else %>
            &#9734;
          <% end%>
        <% end %>
      </section>
      <section class="main-content-form">
        <form name="contactForm">
          <div class="form-group">
            <label for="checkIn">Check In</label>
            <input
              id="checkIn"
              class="form-control"
              type="date"
              name="checkIn"
              onchange="handler1(event);"
              required
            />
          </div>

          <div class="form-group">
            <label for="checkOut">Check Out</label>
            <input
              id="checkOut"
              class="form-control"
              type="date"
              name="checkOut"
              onchange="handler2(event);"
              required
            />
          </div>

          <div class="form-group">
            <label for="firstName">First Name</label>
            <input
              id="firstName"
              class="form-control"
              type="text"
              name="firstName"
              placeholder="Jon"
              required
            />
          </div>

          <div class="form-group">
            <label for="lastName">Last Name</label>
            <input
              id="lastName"
              class="form-control"
              type="text"
              name="lastName"
              placeholder="Doe"
              required
            />
          </div>

          <div class="form-group">
            <label for="phone">Phone</label>
            <input
              id="phone"
              class="form-control"
              type="text"
              name="phone"
              placeholder="+40 731 660 186"
              required
            />
          </div>

          <div class="form-group">
            <label for="email">Email address</label>
            <input
              name="email"
              type="email"
              class="form-control"
              id="email"
              placeholder="name@example.com"
              required
            />
          </div>

          <div class="form-group">
            <label for="attendees">Scope</label>
            <select class="form-control" id="attendees" name="attendees">
              <option value="0">Not specified</option>
              <option value="1">Business</option>
              <option value="2">Leisure</option>
            </select>
          </div>

          <div class="form-group">
            <label for="message">Message (optional)</label>
            <textarea
              id="message"
              class="form-control"
              name="message"
              placeholder="I want a room at a higher floor .."
              rows="10"
              cols="40"
            ></textarea>
          </div>

          <div id="errorAlert" class="error"></div>

          <div class="form-group">
            <button type="button" class="btn btn-primary">
              Submit
            </button>
          </div>
        </form>

        <div id="successMessage" class="success hidden">
          Booking request successfully sent!
        </div>
      </section>
    </section>

    <section class="details">
      <section class="price" id="total-price">
        <p>$ <strong id="trip-price"></strong> / trip</p>
        <p><strong id="nights"></strong> nights</p>
      </section>
      <section class="host-details">
        <section class="details-item">
          <%= image_tag("icon-user.png", alt: "user-logo", width: 50, height: 50)%>
          <div class="details-item-text">
            <h3>Your host</h3>
            <h3><%= @offer.host_name %></h3>
          </div>
        </section>
        <section class="details-item">
          <%= image_tag("icon-clock.png", alt: "clock-logo", width: 50, height: 50)%>
          <div class="details-item-text">
            <h3>Minimum stay</h3>
            <h3><%= @offer.minimum_stay %> nights</h3>
          </div>
        </section>
        <section class="details-item">
          <%= image_tag("icon-placeholder.png", alt: "placeholder-logo", width: 50, height: 50)%>
          <div class="details-item-text">
            <h3>Location</h3>
            <h3><%= @offer.country %></h3>
          </div>
        </section>
      </section>
    </section>
  </section>

  <section class="buttons" id="button-hidden">
    <section class="button-back-resort">
      <a href="#anchorUp">
        <%= image_tag("icon-arrow.png", alt: "icon-arrow", width: 40, height: 40, class: "rotate180")%>
        <h3>Back to Resort</h3>
      </a>
    </section>
  </section>

</main>

<footer class="main-footer">
    <section class="footer-upper-part">
        <section class="main-logo-motto">
            <%= image_tag("logo.png", alt: "logo-image-big")%>
            <%= image_tag("motto.png", alt: "motto")%>
        </section>

        <section class="contact-us">
            <h2>Contact Us</h2>
            <section class="contact-item">
                <%= image_tag("icon-phone.png", alt: "phone-logo")%>
                <a href="tel:+123456789012"><%= @offer.phone %></a>
            </section>
            <section class="contact-item">
                <%= image_tag("icon-email.png", alt: "email-logo", width: "50", height: "50")%>
                <a href="mailto:contact@travel.com"><%= @offer.email %></a>
            </section>
        </section>
    </section>
    <nav class="footer-nav">
        <ul>
            <li><a href="#"><%= image_tag("icon-facebook.png", alt: "facebook-logo", width: "70", height: "70")%></a></li>
            <li><a href="#"><%= image_tag("icon-instagram.png", alt: "instagram-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("icon-twitter.png", alt: "twitter-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("icon-youtube.png", alt: "youtube-logo", width: "60", height: "60")%></a></li>
            <li id="copyright">Copyright @2021</li>
        </ul>
    </nav>
</footer>

<% if current_user %>

  <br><br><br>
  <section class="form-style">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @offer.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @offer.description %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @offer.phone %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @offer.email %>
    </p>

    <p>
      <strong>Country:</strong>
      <%= @offer.country %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @offer.location %>
    </p>

    <p>
      <strong>Meals:</strong>
      <%= @offer.meals %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @offer.price %>
    </p>

    <p>
      <strong>Stars:</strong>
      <%= @offer.stars %>
    </p>

    <p>
      <strong>Cleaning:</strong>
      <%= @offer.cleaning %>
    </p>

    <p>
      <strong>Food:</strong>
      <%= @offer.food %>
    </p>

    <p>
      <strong>Staff:</strong>
      <%= @offer.staff %>
    </p>

    <p>
      <strong>Confort:</strong>
      <%= @offer.confort %>
    </p>

    <p>
      <strong>Host name:</strong>
      <%= @offer.host_name %>
    </p>

    <p>
      <strong>Minimum stay:</strong>
      <%= @offer.minimum_stay %>
    </p>

    <% if @offer.image.attached? %>
      <p>
        <strong>Image</strong>
        <%= image_tag @offer.image.variant(resize: "500x500") %>
      </p>
    <% end %>

    <%= link_to 'Edit', edit_offer_path(@offer) %> |
    <%= link_to 'Back', offers_path %>
  </section>
<% end %>

<script>
  document.getElementById("offer-price").value = <%= @offer.price%>;
</script>

<%= javascript_include_tag 'script_offer'%>

app/views/pages/contact.html.erb
<header class="main-header">
  <nav class="main-nav">
      <figure class="nav-logo">
          <%= image_tag("logo.png", alt: "logo-image-small", class: "logo invert-color")%>
      </figure>
      <ul>
          <li><%= link_to offers_path do %>Home<% end %></li>
          <li><a>|</a></li>
          <li><%= link_to contact_path do %>Contact<% end %></li>
      </ul>
  </nav>
</header>

<main class="main-content-special">
  <section class="main-content-special-contact">
    <h2>Take a Look Here</h2>
    <section class="contact-item-special">
      <%= image_tag("icon-facebook.png", alt: "facebook-logo", width: "50", height: "50")%>
      <a href="#">www.facebook.com/travel</a>
    </section>
    <section class="contact-item-special">
      <%= image_tag("icon-instagram.png", alt: "instagram-logo", width: "50", height: "50")%>
      <a href="#">www.instagram.com/travel</a>
    </section>
    <section class="contact-item-special">
      <%= image_tag("icon-youtube.png", alt: "youtube-logo", width: "50", height: "50")%>
      <a href="#">www.youtube.com/travel</a>
    </section>

    <h2>Visit us</h2>
    <section class="contact-item-special">
      <%= image_tag("icon-location.png", alt: "location-pin-logo", width: "50", height: "50")%>
      <a href="#">Brașov, Romania</a>
    </section>
    <section class="contact-item-special">
      <%= image_tag("icon-phone.png", alt: "phone-logo", width: "50", height: "50", class: "invert-color")%>
      <a href="#">+ 1234 5678 9012</a>
    </section>
    <section class="contact-item-special">
      <%= image_tag("icon-email.png", alt: "email-logo", width: "50", height: "50", class: "invert-color")%>
      <a href="mailto:contact@travel.com">contact@travel.com</a>
    </section>
  </section>

  <section class="main-content-special-form">
    <h2>Contact</h2>
    <form name="contactForm">
      <div class="form-group-special">
        <label for="firstName">First Name</label>
        <input
          id="firstName"
          class="form-control"
          type="text"
          name="firstName"
          placeholder="Jon"
          required
        />
      </div>

      <div class="form-group-special">
        <label for="lastName">Last Name</label>
        <input
          id="lastName"
          class="form-control"
          type="text"
          name="lastName"
          placeholder="Doe"
          required
        />
      </div>

      <div class="form-group-special">
        <label for="phone">Phone</label>
        <input
          id="phone"
          class="form-control"
          type="text"
          name="phone"
          placeholder="+40 731 660 186"
          required
        />
      </div>

      <div class="form-group-special">
        <label for="email">Email address</label>
        <input
          id="email"
          name="email"
          type="email"
          class="form-control"
          placeholder="name@example.com"
          required
        />
      </div>

      <div class="form-group-special">
        <label for="message">Message</label>
        <textarea
          id="message"
          class="form-control"
          name="message"
          placeholder="I need an offer for a 7 nights holiday ..."
          rows="10"
          cols="40"
          required
        ></textarea>
      </div>

      <div id="errorAlert" class="error"></div>

      <div class="form-group-special">
        <button type="button" class="btn btn-primary invert-color">
          Submit
        </button>
      </div>
    </form>

    <div id="successMessage" class="success hidden">
      Message sent successfully!
    </div>

  </section>
</main>

<footer class="main-footer-special">
    <nav class="footer-nav-special">
        <ul>
            <li><a href="#"><%= image_tag("icon-facebook.png", alt: "facebook-logo", width: "70", height: "70")%></a></li>
            <li><a href="#"><%= image_tag("icon-instagram.png", alt: "instagram-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("icon-twitter.png", alt: "twitter-logo", width: "50", height: "50")%></a></li>
            <li><a href="#"><%= image_tag("icon-youtube.png", alt: "youtube-logo", width: "60", height: "60")%></a></li>
            <li id="copyright">Copyright @2021</li>
        </ul>
    </nav>
</footer>

<%= javascript_include_tag 'script'%>